config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  get 'reports/graph'

  resources :tags

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'home#splash'
  get '/dashboard', to: 'home#dashboard'
  get 'mfa_new', to: 'home#mfa_new'
  post '/bank_create', to: 'home#bank_create'
  post '/plaidComplete', to: 'home#plaid_hook'
  post '/mfa_save', to: 'home#mfa_save'
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if name == 'success' %>
    <div class="alert alert-success">
  <% elsif name == 'notice' %>
    <div class="alert alert-danger">
  <% else %>
    <div class="alert alert-info">
  <% end %>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="nav-wrapper">
  <%= link_to root_path do %>
    <h2 class="nav-header-text">Spending</h2>
  <% end %>
  <div>
    <ul class="nav-links-wrapper">
      <li class="nav-link">
        <%= link_to dashboard_path do %>
          <%= fa_icon "align-justify" %>
          <p>Transactions</p>
        <% end %>
      </li>
      <li class="nav-link">
        <%= link_to '/reports/index' do %>
          <%= fa_icon "pie-chart" %>
          <p>Reports</p>
        <% end %>
      </li>
      <li class="nav-link"> <%= link_to tags_path do %>
          <%= fa_icon "tag" %>
          <p>Tags</p>
        <% end %>
      </li>
      <li class="nav-link">
        <%= link_to destroy_user_session_path, method: :delete do %>
          <%= fa_icon "sign-out" %>
          <p>Sign Out</p>
        <% end %>
      </li>
    <ul>
  </div>
  <div class="clearfix"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spending</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body>

  <% if !current_user %>
    <div class="background-hero"><div class="shade"></div></div>
  <% else %>
    <div class="top peter-river"></div>
    <div class="top turquoise"></div>
    <div class="top nephritis"></div>
    <div class="top alizarin"></div>
    <div class="top orange"></div>
  <% end %>

  <div class="container">

  <% if current_user %>
    <%= render partial: 'layouts/navigation' %>
  <% end %>

    <%= yield %>
  </div>

</body>
</html>